# for local development
version: '3.10'
services:
  frontend:
    build:
      context: ./frontend
      target: 'base'
    ports:
    - '8080:8080'
    volumes:
    - './frontend:/app'
    - '/app/node_modules'
    command: npm run dev
  backend:
    build:
      context: ./backend
      target: 'base'
    ports:
    - '1337:1337'
    volumes:
    - './backend:/app'
    - '/app/node_modules'
    command: npm run dev
