# for production deployment
services:
  frontend:
    build:
      context: ./react-frontend
      target: 'base'
    ports:
    - '8080:8080'
    command: sh -c "npm run build && npm run preview"
    env_file:
    - ./react-frontend/.env
    environment:
    - NODE_ENV=production
    - VITE_API_BASE_URL=http://enciclopedia.iea.usp.br:1337/api
  backend:
    build:
      context: ./backend
      target: 'base'
    ports:
    - '1337:1337'
    command: npm run start
    env_file:
    - ./backend/.env
    environment:
    - NODE_ENV=production
    - CORS_ORIGIN=http://enciclopedia.iea.usp.br:8080