# for production deployment
version: '3.10'
services:
  frontend:
    build:
      context: ./react-frontend
      target: 'production'
    ports:
    - '8080:8080'
    command: sh -c "npm run build && npm run preview"
    environment:
    - NODE_ENV=production
  backend:
    build:
      context: ./backend
      target: 'production'
    ports:
    - '1337:1337'
    command: sh -c "npm run build && npm run start"
    environment:
    - NODE_ENV=production
    - CORS_ORIGIN=http://enciclopedia.iea.usp.br:8080