name: CI/CD Enciclopedia

on:
  push:
    branches: ["master"]
    paths:
      - 'backend/**'
      - 'react-frontend/**'
  pull fequest:
    branches: ["master"]
    paths:
      - 'backend/**'
      - 'react-frontend/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: |
           backend/package-lock.json
           react-frontend/package-lock.json

      # BACKEND
      - name: Install & Test Backend
        working-directory: backend
        env:
          DATABASE_URL: postgres://test:test@localhost:5432/test
          SUPABASE_URL: https://fake.supabase.co
          SUPABASE_ANON_KEY: fake-key
          RESEND_API_KEY: re_fake_api_key_para_ci 
          FROM_EMAIL: test@fake.usp.br
          CLOUDINARY_API_KEY: fake_api_key
          CLOUDINARY_API_SECRET: fake_api_secret
          CLOUDINARY_CLOUD_NAME: fake_cloud_name
          JWT_SECRET: EstaFraseTemExatos32Caracteres!!
           
        run: |
          npm ci # 
          npm test

      # FRONTEND
      - name: Install & Build Frontend
        working-directory: react-frontend
        run: |
          npm ci
          npm run build

  deploy:
    needs: ci 
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 2212
          command_timeout: 20m 
          script: |
            set -e

            cd ~
            
            echo "Atualizando código..."
            git pull origin master

            echo "Derrubando containers"
            sudo docker compose down

            echo "Subindo containers..."
            sudo docker compose -f docker-compose.prod.yml up --build -d

            echo "Limpando imagens antigas..."
            sudo docker image prune -f

            echo "Deploy finalizado com sucesso!"
